// Generated by `bun init`

interface ImportMetaEnv {
  readonly BUN_PUBLIC_API_URL?: string;
  /** Devnet (or matching server cluster) RPC for treasury invest + confirmations */
  readonly BUN_PUBLIC_SOLANA_RPC_URL?: string;
  /** Mainnet RPC for submitting Jupiter versioned transactions when server uses Jupiter */
  readonly BUN_PUBLIC_SOLANA_JUPITER_RPC_URL?: string;
  /** Optional override if server config does not expose treasury pubkey */
  readonly BUN_PUBLIC_INVEST_TREASURY_PUBKEY?: string;
}

interface ImportMeta {
  readonly env: ImportMetaEnv;
}

declare module "*.svg" {
  /**
   * A path to the SVG file
   */
  const path: `${string}.svg`;
  export = path;
}

declare module "*.module.css" {
  /**
   * A record of class names to their corresponding CSS module classes
   */
  const classes: { readonly [key: string]: string };
  export = classes;
}
